version: '3'

services:
  api:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    links:
      - db
    environment:
      MIX_ENV: "test"
  db:
    image: mongo
    restart: always
    ports:
      - "2717:2717"

volumes:
  db: {}
