#!/usr/bin/groovy
node {
    def rtGradle = Artifactory.newGradleBuild()
    stage('Gradle build') {
        rtGradle.tool = "Gradle-2.4"
        buildInfo = rtGradle.run rootDir: ".", buildFile: 'build.gradle', tasks: 'clean test'
    }
}